//
// Created by mitom on 2021/7/18.
//

#ifndef MATH_DEFINES_H
#define MATH_DEFINES_H

#define MATH_NAMESPACE_BEGIN namespace math {
#define MATH_NAMESPACE_END }

#define MATH_CALCULATE_NAMESPACE_BEGIN namespace calculate {
#define MATH_CALCULATE_NAMESPACE_END }

MATH_NAMESPACE_BEGIN

MATH_CALCULATE_NAMESPACE_BEGIN  MATH_CALCULATE_NAMESPACE_END

MATH_NAMESPACE_END

#endif //MATH_DEFINES_H
